import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  AppBar,
  Box,
  Container,
  Toolbar,
  Typography,
} from "@mui/material";
import { Adb } from "@mui/icons-material";
import Link from "next/link";
import AppProviders from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppBar position="fixed">
          <Container maxWidth="xl">
            <Toolbar disableGutters sx={{ gap: 2 }}>
              <Adb sx={{ mr: 1 }} />
              <Typography
                variant="h6"
                noWrap
                component="a"
                sx={{
                  mr: 2,
                  display: { xs: "none", md: "flex" },
                  fontFamily: "monospace",
                  fontWeight: 700,
                  letterSpacing: ".3rem",
                  color: "inherit",
                  textDecoration: "none",
                }}
              >
                LOGO
              </Typography>
              <Box flexGrow={1} />
              <Box>
                <Link href="/stocks">Stocks</Link>
              </Box>
              <Box>
                <Link href="/news">News</Link>
              </Box>
            </Toolbar>
          </Container>
        </AppBar>
        <Container maxWidth="xl" sx={{ paddingY: 5 }}>
          <Toolbar />
          <AppProviders>{children}</AppProviders>
        </Container>
      </body>
    </html>
  );
}
